source "https://rubygems.org"
gem "alembic-jekyll-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-mentions"
gem "jekyll-sitemap"
gem "jekyll-mentions"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"
gem "jekyll-default-layout"
gem "jekyll-feed"
gem "jekyll-commonmark"
gem "jekyll-include-cache"
gem "jemoji"
gem 'commonmarker'
gem 'jekyll-feed'
gem 'kramdown-parser-gfm'
# gemspec
