---
site_name: Nithish Duvvuru
site_description: My personal Notes 
site_author: Nithish Duvvuru
site_url: https://nithish96.github.io/

theme:
  name: material
  logo: img/logo.bmp
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
repo_name: nithish96/nitish96.github.io
repo_url: https://github.com/nithish96/nithish96.github.io
